# Generated by Django 4.2.8 on 2024-12-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzeResult',
        ),
    ]
